[package]
name = "pace-rs"
authors = ["the pace-rs team"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/pace-rs/pace"
license = "AGPL-3.0-or-later"
categories = ["command-line-utilities"]
keywords = ["cli"]
description = "pace - timetracking for the command line"


[dependencies]
clap = "4"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"

[dependencies.abscissa_core]
version = "0.7.0"
# optional: use `gimli` to capture backtraces
# see https://github.com/rust-lang/backtrace-rs/issues/189
# features = ["gimli-backtrace"]

[dev-dependencies]
abscissa_core = { version = "0.7.0", features = ["testing"] }
once_cell = "1.2"

