[workspace]
pr_draft = true
dependencies_update = true

[[package]]
name = "pace-rs"
changelog_include = [
  "pace_cli",
  "pace_core",
] # include commits from these package in the changelog
changelog_update = true
# release-plz doesn't work well with cargo-dist, so we deactivate releases here
# and let cargo-dist handle the release
git_release_enable = false
# but we want a tag and to publish to crates.io
git_tag_enable = true
publish = true

[changelog]
protect_breaking_commits = true
