[build]
rustdocflags = ["--document-private-items"]
# rustflags = "-C target-cpu=native -D warnings"
# rustflags = ["-Dwarnings"]
incremental = false

# [target.x86_64-pc-windows-msvc]
# linker = "rust-lld.exe"

# NOTE: you must manually install https://github.com/michaeleisel/zld on mac. you can easily do this with the "brew" package manager:
# `brew install michaeleisel/zld/zld`
# [target.x86_64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"]

# [target.x86_64-unknown-linux-gnu]
# linker = "/usr/bin/clang"
# rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
