//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub guid: String,
    pub category: String,
    pub description: Option<String>,
}

#[derive(DeriveIden)]
pub enum Categories {
    Table,
    Guid,
    Category,
    Description,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activities_categories::Entity")]
    ActivitiesCategories,
}

impl Related<super::activities_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivitiesCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
