//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod activities;
pub mod activities_categories;
pub mod activities_tags;
pub mod activity_kinds;
pub mod activity_status;
pub mod categories;
pub mod descriptions;
pub mod tags;
