[package]
name = "pace_core"
version = "0.7.0"
authors = { workspace = true }
categories = { workspace = true }
edition = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = "1.74.1"
description = "pace-core - library to support timetracking on the command line"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
include = [
  "LICENSE",
  "README.md",
  "CHANGELOG.md",
  "src/**/*",
  "Cargo.toml",
]

[dependencies]
async-condvar-fair = "1.0.0"
chrono = { version = "0.4.34", features = ["serde"] }
directories = "5.0.1"
displaydoc = "0.2.4"
futures = "0.3.30"
getset = "0.1.2"
itertools = "0.12.1"
log = "0.4.20"
rusqlite = { version = "0.30.0", features = ["bundled", "chrono", "uuid"] }
serde = "1.0.196"
serde_derive = "1.0.196"
strum = "0.26.1"
strum_macros = "0.26.1"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["sync", "rt", "rt-multi-thread", "time"] }
toml = { version = "0.8.10", features = ["indexmap", "preserve_order"] }
typed-builder = "0.18.1"
uuid = { version = "1.7.0", features = ["serde", "fast-rng", "v7"] }

[dev-dependencies]
rstest = "0.18.2"

[lints.rust]
unsafe_code = "forbid"
# missing_docs = "warn"
rust_2018_idioms = "warn"
trivial_casts = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
bad_style = "warn"
dead_code = "warn"
improper_ctypes = "warn"
# missing_copy_implementations = "warn"
# missing_debug_implementations = "warn"
non_shorthand_field_patterns = "warn"
no_mangle_generic_items = "warn"
overflowing_literals = "warn"
path_statements = "warn"
patterns_in_fns_without_body = "warn"
trivial_numeric_casts = "warn"
unused_results = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unconditional_recursion = "warn"
unused = "warn"
unused_allocation = "warn"
unused_comparisons = "warn"
unused_parens = "warn"
while_true = "warn"

[lints.clippy]
# pedantic = "warn"
# nursery = "warn"
enum_glob_use = "warn"
correctness = "warn"
suspicious = "warn"
complexity = "warn"
perf = "warn"
cast_lossless = "warn"
default_trait_access = "warn"
doc_markdown = "warn"
manual_string_new = "warn"
match_same_arms = "warn"
semicolon_if_nothing_returned = "warn"
trivially_copy_pass_by_ref = "warn"
module_name_repetitions = "allow"
