[package]
name = "pace_core"
version = "0.8.0"
authors = { workspace = true }
categories = { workspace = true }
edition = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = "1.74.1"
description = "pace-core - library to support timetracking on the command line"

include = [
  "LICENSE",
  "README.md",
  "CHANGELOG.md",
  "src/**/*",
  "Cargo.toml",
]

# TODO!: Use features for adding optional dependencies for testing and merging etc.
# [features]
# default = []
# testing = ["dep:arbitrary"]

[dependencies]
# We'd rather have this only for testing but we do integration tests, and this wouldn't be build then
arbitrary = { version = "1", features = ["derive"] }
chrono = { version = "0.4.34", features = ["serde"] }
directories = "5.0.1"
displaydoc = "0.2.4"
getset = "0.1.2"
itertools = "0.12.1"
log = "0.4.20"
merge = "0.1.0"
rayon = "1.8.1"
rusqlite = { version = "0.31.0", features = ["bundled", "chrono", "uuid"] }
serde = "1.0.197"
serde_derive = "1.0.197"
strum = "0.26.1"
strum_macros = "0.26.1"
thiserror = "1.0.57"
toml = { version = "0.8.10", features = ["indexmap", "preserve_order"] }
typed-builder = "0.18.1"
ulid = { version = "1.1.2", features = ["serde"] }

[dev-dependencies]
rstest = "0.18.2"
similar-asserts = { workspace = true }

[lints]
workspace = true
