[package]
name = "pace_core"
version = "0.5.1"
authors = { workspace = true }
categories = { workspace = true }
edition = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = "1.74.1"
description = "pace-core - library to support timetracking on the command line"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
include = [
  "LICENSE",
  "README.md",
  "CHANGELOG.md",
  "src/**/*",
  "Cargo.toml",
]

[dependencies]
async-condvar-fair = "1.0.0"
chrono = { version = "0.4.34", features = ["serde"] }
directories = "5.0.1"
futures = "0.3.30"
getset = "0.1.2"
itertools = "0.12.1"
log = "0.4.20"
rusqlite = { version = "0.30.0", features = ["bundled", "chrono", "uuid"] }
serde = "1.0.196"
serde_derive = "1.0.196"
strum = "0.26.1"
strum_macros = "0.26.1"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["sync", "rt", "rt-multi-thread", "time"] }
toml = { version = "0.8.10", features = ["indexmap", "preserve_order"] }
typed-builder = "0.18.1"
uuid = { version = "1.7.0", features = ["serde", "fast-rng", "v7"] }

[dev-dependencies]
rstest = "0.18.2"
