name: Test Coverage

on: [push]
jobs:
  test:
    name: generate coverage report
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.1.0
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: pace-rs/pace
            fail_ci_if_error: true