name: Lint Markdown / Toml

on:
  pull_request:
  push:
    branches: [main]
  merge_group:
    types: [checks_requested]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dprint/check@v2.2

  result:
    name: Result (Style)
    runs-on: ubuntu-latest
    needs:
      - style
    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"